clone_folder: c:\projects\pandoc

environment:
  matrix:
    - CONDA: C:\Miniconda37-x64

install:
  - cmd: set PATH=%PATH%;%CONDA%;%CONDA%\Scripts
  - cmd: cd c:\projects\pandoc
  - cmd: conda env create -n pandoc -f environment.yml
  - cmd: activate pandoc
  - cmd: pip install .
        
test_script:
  - cmd: python test.py
