name: pandoc
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandoc=2.14.1
  - plumbum
  - ply
  - pip
  - setuptools
  - wheel
  - twine
  - strictyaml
  - black
  - pip:
    - mkdocs
    - mkdocs-material
